###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

mailhog:
  image: phpdockerio/mailhog:latest
  container_name: mailhog
  ports:
    - "8081:8025"

mysql:
  image: mysql:5.7
  container_name: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root-drupal
    - MYSQL_DATABASE=drupal
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=drupal
  volumes:
      - ./dumps:/docker-entrypoint-initdb.d
  ports:
    - "33060:3306"

webserver:
  image: phpdockerio/nginx:latest
  container_name: webserver
  volumes:
      - .:/var/www/drupal
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  links:
   - php-fpm

php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: php-fpm
  volumes:
    - .:/var/www/drupal
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
  links:
    - mailhog
    - mysql
